/* import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
} */
import React from 'react';
import '@/assets/styles/globals.css';

export const metadata = {
	title: 'mARB',
	description:
		'We help provider networks (hospitals and doctors) quickly settle out of network medical claims with insurance payers.',
	keywords:
		'marb, health, healtcare, claims, out of network, out of network claims',
};

const MainLayout = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<div>{children}</div>
			</body>
		</html>
	);
};

export default MainLayout;
